// GENERATED FILE - DO NOT EDIT
// Generated by versioner at 2026-02-19T19:52:56.482075Z

/// Version information generated at build time.
///
/// This class contains static fields and methods for accessing
/// version information embedded during the build process.
class TomVersionInfo {
  TomVersionInfo._();

  /// Package version from pubspec.yaml
  static const String version = '1.0.1';

  /// Build timestamp (ISO 8601 UTC format)
  static const String buildTime = '2026-02-19T19:52:56.482075Z';

  /// Git commit hash (short form)
  static const String gitCommit = '51cd730';

  /// Build number (increments with each build)
  static const int buildNumber = 6;

  /// Dart SDK version used to build
  static const String dartSdkVersion = '3.11.0';

  /// Short version string: version + build number
  /// Example: "1.0.0+42"
  static String get versionShort => '$version+$buildNumber';

  /// Medium version string: version + build number + git commit + build time
  /// Example: "1.0.0+42.abc1234 (2026-02-01T10:30:00.000Z)"
  static String get versionMedium => '$version+$buildNumber.$gitCommit ($buildTime)';

  /// Long version string: includes all available information including SDK version
  /// Example: "1.0.0+42.abc1234 (2026-02-01T10:30:00.000Z) [Dart 3.x.x]"
  static String get versionLong => '$version+$buildNumber.$gitCommit ($buildTime) [Dart $dartSdkVersion]';
}
