/// D4rt GEN-079 Relaxer Wrappers for tom_vscode_bridge
///
/// Auto-generated wrapper classes and factory functions for generic
/// type relaxation. These enable `extractBridgedArg<Base<Arg>>` to
/// succeed when the runtime value has `<dynamic>` type arguments.
///
/// DO NOT EDIT — generated by d4rtgen relaxer generator.
library;

// ignore_for_file: unused_import, invalid_implementation_override, deprecated_member_use, sort_child_properties_last, invalid_use_of_protected_member, unnecessary_non_null_assertion, invalid_use_of_visible_for_testing_member, unused_local_variable, unintended_html_in_doc_comment, non_constant_identifier_names, unreachable_switch_case, must_call_super, no_logic_in_create_state, unused_field, unnecessary_cast, no_leading_underscores_for_local_identifiers, prefer_is_empty, unnecessary_question_mark, empty_constructor_bodies, prefer_const_constructors_in_immutables, prefer_final_fields, use_key_in_widget_constructors, annotate_overrides, unnecessary_import


// GEN-095: No relaxers or RC-2 generic constructors reachable via barrels
// Emitting empty stubs so the dartscript registration calls
// to registerRelaxers() / registerGenericConstructors() resolve.

/// No-op: no GEN-079 relaxer wrappers for this package.
void registerRelaxers() {}

/// No-op: no RC-2 generic constructor factories for this package.
void registerGenericConstructors() {}
